# Generated by Django 4.2 on 2023-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='my_day',
            field=models.CharField(blank=True, choices=[('my_day', 'Мой день')], max_length=10),
        ),
    ]
