# Generated by Django 4.2 on 2023-05-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_my_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'Задачи', 'verbose_name_plural': 'Задачи'},
        ),
    ]
