# Generated by Django 4.2 on 2023-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='my_day',
            field=models.BooleanField(blank=True, max_length=10),
        ),
    ]
